###### 5CCP: Computational Laboratory 

## Module Coordinators: 
#### Cedric Weber (cedric.weber@kcl.ac.uk)
#### Joe Bhaseen (joe.bhaseen@kcl.ac.uk)

## Section 1 : A refresher to Python Jupyter Notebook and NumPy, Simple data analysis and manipulation

From the first year computing lecture, you should be familiar with:
 - Assignment of variables and basic arithmetic
 - Manipulation and formatting of 'string' objects
 - If statements, conditionals and comparisons
 - 'While' loops for iterating until a condition is met
 - Lists and iterating over elements of a list with 'for' loops
 - Creating your own functions
 - Reading and writing to files
 - Plotting functions
 
If you want to refresh your knowledge of these concepts, it will be worth revisiting the previous sessions notebooks and completing the tasks if you have been unable to, as well as watching the VodCasts associated with each session in the 5CCP module.
We'll provide plenty of support, so stay tuned in!

In this session, we are refreshing useful notions and tools in Python.

You will be routinely dealing in the coming weeks with algeabric operations that sparks quite a few headaches when it comes to solving them. There are simple algorithms and techniques to solve those that are directly available at hand in Python, or more precisely via the external module NumPy. 

NumPy provides in particular:

- extension package to Python for dealing with arrays, 

- designed for scientific computation (convenience), 

- Also known as array oriented computing.

We are going to start off with looking at arrays, and their implementation in Python. Think of arrays as collection of variables, united under the same entity. The array is like any other variables that you have encountered so far, but it has an extra "index". This index identifies which element of the array you want to extract, or modify. To help illustrate this point, let's have a look at this example:


In [93]:
x1=1
x2=2
x3=3
x4=4
x5=5
x6=6
x7=7
x8=8
x9=9

print (x1, x2, x3, x4, x5, x6, x7, x8, x9)

1 2 3 4 5 6 7 8 9


In this example, we are setting 9 variables to 1-9 and print their values. This is a very cumbersome operation, that could be simplified by using a "for loop". The problem is that there is no systematic way to access the variables x1,x2, .. as at present they are independent. 

The array NP is constructed as follow in NumPy (we import here the numpy module as np!)

In [1]:
import numpy as np

a = np.array([0, 1, 2, 3])
a



array([0, 1, 2, 3])

Very minor detail: note that in the example above, the formatting is involving comas in the list of elements of the array. If instead, you use the print(a) statement, it will provide a nicer formatting, and align the elements by row/columns, and remove the comas, see for example:


In [2]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


Here, the array "a" has 4 elements, with the values set to respectively 0,1,2 and 3. We can now print all the elements contained in the array:

Or alternatively print only one of the array element:

In [7]:
import numpy as np
a = np.array([0, 3, 5, 3])
print( a[1] )

3


### Why are arrays useful?

The array might contain values of an experiment or from a simulation at different discrete time steps,
a signal recorded by a measurement device, such as sound wave or signal intensity, pixels from an image with an index which is the grey-level or colour, 3-D data measured at different carthesian coordinates (MRI scan), etcetera. Why are arrays useful? Imagine that now we need to store a thousand data points, it would be extremely time consuming to do it by hand and declare as many variables. With arrays, we can do it in a breeze! 




A few useful functions that provide some information about the dimension and shape of your arrays are : 

- a.ndim

- a.shape

- len(a) 

They provide the dimension of the array (in the case studied so far, those are one dimensional), the shape, e.g. the number of elements for each dimension, and the length, or total number of elements in the array.





In [8]:
a = np.array([0, 1, 2, 3])
a

print (a.ndim)

print (a.shape)

print(len(a))


1
(4,)
4


As hinted above, arrays can also have more than one dimension, think of it as a "table", where entries can be entered by lines or columns.

In 2D, the first dimension corresponds to lines, the second to columns.
for an array a with more than one dimension, the rows are provided one by one. For example, if an array is a 2 x 3 matrix (table), with two lines of three elements,
it will be written as:

`b = np.array([[0, 1, 2], [3, 4, 5]])`

The first line of the matrix is: 0,1,2; the second line of the matrix is: 3,4,5.


In [9]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

print(b)

print(b.ndim)

print(b.shape)



[[0 1 2]
 [3 4 5]]
2
(2, 3)


### Exercice 1: Simple arrays

Your first exercice is to create a two dimensional array with dimension 2x10 (two rows of 10 elements). The first row should contain odd numbers counting backwards, and the second row the even numbers counting forward. Here, you can make use of the for loop in Python, or alternatively fill in the arrays element by element.


In [6]:
import numpy as np

b = np.array([[i for i in range(9,-1,-2)], [j for j in range(0,10,2)]])

print(b)





[[9 7 5 3 1]
 [0 2 4 6 8]]


### NumPy Array Creation

There are different ways to create arrays from scratch with NumPy:

- zeros(shape) will create an array filled with 0 values with the specified shape. The default dtype is float64.

- ones(shape) will create an array filled with 1 values. It is identical to zeros in all other respects.

- arange() will create arrays with regularly incrementing values. 

- linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.

A few examples here:


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [20]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

### Using arrays for plotting 1D curves rapidly

Another usage of arrays is for scientific plotting. Imagine that you want to plot a either a mathematical function or a data set, you might need to define discretized values of this function. 

A simple way to achieve this is to choose a space interval along the horizontal x axis, and a corresponding number of data points. The function np.linspace is very useful for this, as it guarantees a fixed number of data point. 

Below we plot the function sin(x) evaluated between 0 and 6.3 with 20 data points.

Reminder: the plot function takes the optional argument 'o', which produces a dotted plot instead of a line plot.


In [8]:
import numpy as np
import matplotlib.pyplot as plt

a= np.linspace(0., 6.3, 20) 

plt.xlabel('x', fontsize=26)
plt.ylabel('Sin(x)', fontsize=26)
plt.plot(a, np.sin(a) ,'o' )
plt.plot(a, np.sin(a)  )

plt.show()


Note that if you want top plot lines instead a dotted curve, you can simply remove the 'o' argument in the plot function, see here:

## Exercise 2, introduction to random numbers and random walks

In this problem, we are going to study the problem of the poor-man's random walk. 
As after a long night out, the poor-man's vision is
not performing as well as it should, he walks randomly and shuffles steps to its left or right, with equivalent properties (of course this is a one dimensional simplification of the trajectory, which confines the random walk but let's go with this for sake of simplicity).

We'll denote a left step as `-1` and a right
step as `+1`. We can track his steps by an array containing a list of `-1` and `+1`,
where the indices of this array correspond to the time axis, and at each time we know
the shuffled jumps (left or right).

2.1: construct a one dimensional array of size tmax=200, that is filled with random -1 and +1,
describing the man's trajectory. Here NumPy comes in again very handy, as the function:
```
np.random.random_integers(0, 1, tmax )
```
provides an array with random 0 and 1. You'll need to use global array operations to obtain a corresponding result where the zeros are replaced with '-1'. 

2.2: Calculate the exact distance travelled by poor-man as a function of time, d(t),
and the square of the distance, d(t)^2. Plot both functions. 

As unfortunately this story repeats itself (a thousand times), we obtain a sample
of a 1000 realizations of the random trajectory. We want now to compute the average
mean square distance as a function of time. 

2.3: Use the function below with nmax=1000 to generate a table with :
```
np.random.random_integers(0, 1, (nmax,tmax) )
```
which corresponds to nmax trajectories and time tmax. As you did in 2.2, find a simple
algorithm to replace the zeros with '-1'.

2.4: Calculate, by using array operations, the distance as a function of time for each trajectories

2.5: Calculate the square of these distances

2.6: Average over the nmax stories

2.7: Plot the mean square distance as a function time

2.8: Plot the square root of the mean square distance function with time.

The last result (2.8) can be compared with our knowledge of Newton ballistic motion.
What would be the behavior (linear, quadratic, ...) of the distance as a function of time for a classical object evolving
without any applied force? Does it match with the random walk?  



In [39]:
import numpy as np
import matplotlib.pyplot as plt

tmax= 200

a = np.random.random_integers(0, 1, tmax )


a = (a * 2 ) - 1


a = np.cumsum( a  )

print (a)

plt.xlabel('time', fontsize=26)
plt.ylabel('Distance', fontsize=26)


plt.plot(np.array(range(0,len(a))), a)

plt.show()



[-1  0  1  2  3  2  1  0 -1  0 -1  0 -1  0 -1 -2 -3 -4 -3 -2 -3 -2 -1 -2 -3
 -2 -1  0  1  0  1  0 -1  0 -1  0 -1 -2 -1  0  1  0  1  2  3  2  1  0 -1 -2
 -1  0 -1  0 -1 -2 -1  0 -1  0 -1  0  1  2  3  2  3  4  3  4  5  4  5  4  3
  4  5  4  3  2  1  2  3  4  5  6  5  6  7  8  9 10  9  8  9 10 11 10  9  8
  9  8  9 10  9  8  9  8  7  6  5  4  3  4  5  6  7  8  9 10  9 10 11 12 13
 14 15 16 15 16 15 14 13 14 15 14 13 12 13 14 13 14 13 12 13 14 13 14 15 16
 17 18 17 16 17 16 15 14 13 12 13 14 15 16 17 18 19 20 19 20 21 22 23 22 23
 22 21 20 19 20 19 20 21 22 23 24 25 24 25 26 25 26 27 26 27 26 27 28 29 30]


In [40]:
import numpy as np
import matplotlib.pyplot as plt

tmax=200


a = np.random.random_integers(0, 1, (1000,2000) )

a = (a * 2 ) - 1

a = np.cumsum(a,1)

a = a ** 2

b= np.mean(a,0)

c = [[i, b[i]] for i in range(0,len(b))]


plt.plot(range(0,len(b)), np.sqrt(b))
plt.show()


#### Question: 

Who got the Nobel Prize for this, and for what is the name of the discovery?


Answer :   ....





### Exercise 3, Function integration with Monte Carlo

In this problem, we use random events to calculate the integral of simple functions, in particular
we'd like to obtain the integral of $sin^4(x)$ in the interval $\left[ 0, \pi \right]$

We will apply the following strategy: 

3.1: define an adequate bounding box, for this we need the maximum of the function

3.2: choose random duplets (x,y) lying within this box

3.3: identify whether the point lies below or above the function, increment a counter

3.4: use a for loop to repeat this operation a thousand times

3.5: after the for loop ends, calculate the ratio of the counter and the total number of points

3.6: from the lecture notes, obtain the estimated integral from the size of the box and the ratio obtained in 3.5





In [69]:

def integrate(fxn,a,b,n):
    maxBound = np.amax([fxn(i) for i in np.linspace(a,b,n)])
    return sum([ 1.0/n for point in np.random.rand(n,2) if fxn(float(point[0]) * (b-a) -a) >= (point[1] * maxBound)])* (b-a) * maxBound

print(integrate(lambda x : np.sin(x) ** 4, 0, np.pi, 100000))

1.16999193547


In [ ]:
def cleverIntegrate(fxn,a,b,n):
    